USE HelpdeskGesicBDD;
ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3267C6CFD;
ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3C3534552;
ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3C9486A13;
DROP INDEX IDX_97A0ADA3C3534552 ON ticket;
DROP INDEX IDX_97A0ADA3C9486A13 ON ticket;
DROP INDEX IDX_97A0ADA3267C6CFD ON ticket;
ALTER TABLE ticket
  ADD priorite_calculee SMALLINT NOT NULL DEFAULT 0,
  ADD id_impact INT NOT NULL,
  ADD id_urgence INT NOT NULL,
  DROP note_priorite,
  DROP id_priorite,
  DROP id_statut,
  DROP id_categorie,
  CHANGE niveau_impact statut VARCHAR(255) NOT NULL;
ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3E23E75EA FOREIGN KEY (id_impact) REFERENCES impact (id_impact);
ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3ADE0C2BD FOREIGN KEY (id_urgence) REFERENCES urgence (id_urgence);
CREATE INDEX IDX_97A0ADA3E23E75EA ON ticket (id_impact);
CREATE INDEX IDX_97A0ADA3ADE0C2BD ON ticket (id_urgence);